site_name: Vossler

title: Vossler

logo:
  path: /media/logo.png

header_image:
  - /media/head_background_1.png
  - /media/head_background_2.png   
  - /media/head_background_3.png   
  

footer_image: /media/footer_background.png

reel:
  path: /media/reel2017.mp4
  preview_path: /media/reel2017.mp4
  preview_image:
  embed: false

seemless_video:
  path: 
  preview_path: /media/Vossler_VS_Animal_Loop.mp4
  
