site_name: Vossler

title: Vossler

logo_path: /media/logo.png

header_images:
  - image: /media/head_background_1.png
  - image: /media/head_background_2.png   
  - image: /media/head_background_3.png   
  

footer_image: /media/footer_background.png

reel:
  path: /media/reel2017.mp4
  preview_path: /media/reel2017.mp4
  preview_image:
  embed: false

seemless_video:
  path: 
  preview_path: /media/Vossler_VS_Animal_Loop.mp4

social_media:
  - name: 'Facebook'
    image: 'assets/icon-facebook.png'
    url: 'http://facebook.com'

  - name: 'Instagram'
    image: 'assets/icon-instagram.png'
    url: 'http://instagram.com'

  - name: 'LinkedIn'
    image: 'assets/icon-linkedin.png'
    url: 'http://linkedin.com'

google_analytics:
  html: '<div></div>'
  
